version: '3'
services:
    elastic:
        image: 'elasticsearch:6.6.2'
        ports:
            - '9200:9200'
            - '9300:9300'
        environment:
            - discovery.type=single-node

    mongo:
        image: mongo:4
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: master
            MONGO_INITDB_ROOT_PASSWORD: mORU2nImUvigaVV4C8x9

    mongo-express:
        image: mongo-express:0.49
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: master
            ME_CONFIG_MONGODB_ADMINPASSWORD: mORU2nImUvigaVV4C8x9